### ISSUE TITLE
Limitation access to the APLIC machine-level interrupt domain without PMP entries

### ISSUE THREAD

**Issue by nonufrienko** [riscv/riscv-aia#100]
Can an implementation without PMP restrict access to the APLIC machine-level interrupt domain memory region from a less privileged mode?

Is it acceptable to always report an access fault in such cases?

**Comment by jhauser-us** [comment]
Your question is not really about an APLIC but instead is this:  Can a RISC-V machine implement some form of privilege-specific physical memory protection that is not the PMP specified by the RISC-V Privileged ISA?

I don't have an official answer.  I suggest asking in a forum where the Privileged ISA is discussed.  If you're a member of RISC-V International, you could E-mail the 'tech-privileged' mailing list.  If you're not a member, maybe here:
https://groups.google.com/a/groups.riscv.org/g/isa-dev

**Comment by nonufrienko** [comment]
Ok, thanks
