### ISSUE TITLE
When vsiselect is in the range of 0x070–0x0FF, does access to vsireg2 belong to IMSIC states?

### ISSUE THREAD

**Issue by Jahhow** [riscv/riscv-aia#103]
If the access belong to IMSIC states, then the access can be controled by stateen[58] (IMSIC),
so when mstateen0[58]=0, the access to vsireg2 shall raise illegal-instruction-exception.

Otherwise, if the access does not belong to IMSIC states, then the access should follow this rule in the AIA specification:
> when vsiselect has a value **in the range 0x30–0x3F or 0x70–0xFF**, attempts from M-mode or HS-mode to access alias CSRs vsireg2 through vsireg6 raise an illegal instruction exception, and attempts **from VS-mode to access sireg2 through sireg6 raise a virtual instruction exception**.

**Comment by jhauser-us** [comment]
For the AIA as it currently exists, the answer to the title's question is "no".  The sentence that you quoted is not overridden by `mstateen0` bit 58 (IMSIC) or bit 59 (AIA), only by `mstateen0` bit 60 (CSRIND).

**Comment by Jahhow** [comment]
Thanks for the clarification.
