### ISSUE TITLE
behavior when CLIC implemented and enabled?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-aia#32]
Is it legal to implement both CLIC and AIA extensions?

If so, what effect (if any) does this have on AIA CSRs when CLIC mode is enabled? Do any of them appear hard-wired to zero, like `xie`/`xip` CSRs?

Thanks.

**Comment by jhauser-us** [comment]
> Is it legal to implement both CLIC and AIA extensions?

I believe not.  It's my understanding the two are incompatible.

**Comment by JamesKenneyImperas** [comment]
Thanks.
