### ISSUE TITLE
regarding delegation and child index

### ISSUE THREAD

**Issue by neelgala** [riscv/riscv-aia#5]
If I have three domains A -> B -> C (like figure 4.3 in the spec). 

- Is C considered a child of A i.e. is the index of C a valid value for A's sourcecfg.child_index field ?

- Can A directly delegate an interrupt to C even if B does not delegate the same interrupt to C?

- Lastly, is there a practical scenario where one would require to have A -> (B,D) -> C (more than one child at the same level ?

**Comment by jhauser-us** [comment]
Neel Gala wrote:
> If I have three domains A -> B -> C [...]

In the standard vocabulary of tree graphs, C is not a child of A, but C is a *descendant* of A.  (You are not a child of your grandmother; but you are a descendant of your grandmother.)

Domain A can delegate interrupts only to B, and B can then delegate to C.  Domain A cannot directly delegate an interrupt to C.

The graph A -> (B,D) -> C doesn't look like a tree to me.  The draft spec says "A PLIC’s interrupt domains are arranged in a tree hierarchy".  That means every interrupt domain that is not the root has exactly one parent.  Domain C cannot have both B and D as parents.

**Comment by neelgala** [comment]
thanks.
