### ISSUE TITLE
Does  interrupts  have priority when aplic forward through MSI? How to send MSI if 1023 interrupts arrive simultaneously

### ISSUE THREAD

**Issue by vang2333** [riscv/riscv-aia#60]

**Comment by jhauser-us** [comment]
When an APLIC interrupt domain is configured for MSI delivery, no priority is specified among the enabled-and-pending interrupts.  If 1023 interrupts arrive simultaneously, they may be forwarded in any order.

The example APLIC that is in development prefers to forward lower-numbered interrupts first, but that is simply one choice among many allowed possibilities.

I would recommend that an APLIC implementation at least try to ensure that all interrupts get forwarded eventually.  But the APLIC spec says nothing about how long this might take.  (Just as the RISC-V ISA spec says nothing about how long it takes to execute each instruction.)  The speed of MSI forwarding is entirely a quality-of-implementation issue.
