### ISSUE TITLE
Behavior of accessing vsireg at vsiselect addresses 0x30~0x3f from HS-mode.

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-aia#66]
The AIA spec says that there are no registers at vsiselect addresses 0x30-0x3f (iprio array), and an attempt from VS-mode to access sireg (vsireg) casues a virtual instruction exception when vsiselect has a value in the range 0x30-0x3f.
![image](https://github.com/riscv/riscv-aia/assets/39526191/4e4dfa09-84a8-4b51-a075-1292970e5e86)

What's the behavior of an attempt from HS-mode to access vsireg when vsiselect has a value in the range 0x30-0x3f? The HS-qualified concept in the preliminary privileged spec states that normally raising a virtual instruction exception from VS-mode if it would be valid to execute from HS-mode. Does the vsireg provide a valid constant-zero behavior for HS-mode when vsiselect has a value 0x30-0x3f? Or does it cause an illegal instruction or virtual instruction exception?
![image](https://github.com/riscv/riscv-aia/assets/39526191/acac5bbb-38d5-4464-ba8f-ad8cafd10a6b)

**Comment by jhauser-us** [comment]
Your questions are answered in Section 2.3, "Hypervisor and VS CSRs".  The register locations selected when `vsiselect` is in the range 0x030-0x03F are called *inaccessible*.  The section says:
> For alias CSRs `sireg` and `vsireg`, the hypervisor extension's usual rules for when to raise a virtual instruction exception (based on whether an instruction is HS-qualified ) are not applicable.  The rules given in this section for `sireg` and `vsireg` apply instead, unless overridden by the requirements of Section 2.5, which take precedence over this section when extension Smstateen is also implemented.

And:
> When `vsiselect` has the number of an *inaccessible* register, attempts from M-mode or HS-mode to access `vsireg` raise an illegal instruction exception, and attempts from VS-mode to access `sireg` (really `vsireg`) raise a virtual instruction exception.

**Comment by YenHaoChen** [comment]
Thank you
