### ISSUE TITLE
MVIP.STIP

### ISSUE THREAD

**Issue by jiahzhang** [riscv/riscv-aia#79]
Is it recommended for this alias to be writeable or read-only when menvcfg.STCE is off?

**Comment by jhauser-us** [comment]
An alias of a field is a separate path for accessing the same field, with a single read-only or writable property.  If the field is read-only in one place, then it is read-only at the alias.  If the field is writable in one place, then it is writable at the alias.

AIA Section 5.3, "Interrupt filtering and virtual interrupts for supervisor level", says,
> Bit 5 of `mvip` is an alias of the same bit (STIP) in `mip` when that bit is writable in `mip`.

Hence, whenever `mvip`.STIP is an alias of `mip`.STIP, it must be writable in both places.

(Earlier, the RISC-V documents sometimes said "read-only alias", but those words should have been replaced everywhere by "read-only copy".  If you see any instance of "read-only alias" that remains, please create a GitHub issue for it.)

**Comment by jiahzhang** [comment]
Thanks
