### ISSUE TITLE
ASCII doc broken text

### ISSUE THREAD

**Issue by albert-azcarate** [riscv/riscv-aia#83]
There are plenty of render errors on the new ascii doc release. I checked those on the source latex files and the syntax seems fine. I recompiled the pdf and every error was fixed on my local machine. 
Can it be recompiled and rereleased ?

**Comment by wmat** [comment]
Yes, there is a font issue on Linux with mathematical symbols. I have to fix that today so the GH action works again.

**Comment by wmat** [comment]
Turns out the Makefile was missing the asciidoctor-mathematical requirement.  Fixed on asciidoc branch.  Were there other rendering errors other than latexmath you were seeing?
