### ISSUE TITLE
Clarify "Access control by the state-enable CSRs"

### ISSUE THREAD

**Issue by wissygh** [riscv/riscv-aia#84]
Hi~, when reading about the feature in the spec, I am kind of confused. Could you please clarify the specification for the following feature(in chapter 2.5)：

  Can bit 59 in stateen for riscv64 control access to states of mip/mie?

thanks.
![image](https://github.com/riscv/riscv-aia/assets/41678041/8eb8e693-75de-43a8-affa-b460173ed573)

**Comment by jhauser-us** [comment]
@wissygh:  No bits in `mstateen0` are supposed to affect accesses to M-level CSRs such as `mip` and `mie`.  Hence, I don't understand the question:
> Can bit 59 in stateen for riscv64 control access to states of mip/mie?

The answer would seem to obviously be "No".

**Comment by wissygh** [comment]
> @wissygh: No bits in `mstateen0` are supposed to affect accesses to M-level CSRs such as `mip` and `mie`. Hence, I don't understand the question:
> 
> > Can bit 59 in stateen for riscv64 control access to states of mip/mie?
> 
> The answer would seem to obviously be "No".

Sorry, I made a typo. It should be "sip/sie". It only mentions "sieh/siph" here.
