### ISSUE TITLE
How to define NMI in AIA architecture?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv/riscv-aia#85]
We can define a specific INTID in IMSIC, and the eie is set to 1, which cannot be clear, so this specific INTID can be regarded as NMI. At any time the corresponding eip is set to 1, IMSIC sends an valid NMI to the core.
When the core receives an interrupt with this INTID, it can be regarded as an NMI. 
Whether the above method can be used to implement NMI?

**Comment by jhauser-us** [comment]
> Whether the above method can be used to implement NMI?

Not really, no.

External interrupts at machine level can always be masked by bit `mie`.MEIE, as well as by `mstatus`.MIE, so even though you want to have the specific `eie` bit in an IMSIC interrupt file be always 1, that isn't enough to make this a non-maskable interrupt.  Furthermore, you're not allowed to have an interrupt-enable bit in an IMSIC interrupt file be read-only 1.
