### ISSUE TITLE
regarding holes in idc structures

### ISSUE THREAD

**Issue by neelgala** [riscv/riscv-aia#9]
The idc structures requires 32-bytes but fields for only 20 bytes have been allocated. Are the other 12-bytes reserved or available for custom use? Should they be read-only zeros if accessed or should we raise a bus/slave error?

**Comment by jhauser-us** [comment]
The intro to section 4.5, "Memory-mapped control region for an interrupt domain", says:
> Aside from the registers in Table 4.1 and those listed above for IDC structures, all other bytes in an interrupt domain’s control region are reserved and are implemented as read-only zeros.

If there is a need to designate some of that space for custom use, it could be done.  But currently, all of the unallocated 12 bytes are reserved for future standards; they can't be custom.

**Comment by neelgala** [comment]
thanks.
