### ISSUE TITLE
mtopi/stopi values ​​when mnstatus.NMIE=0

### ISSUE THREAD

**Issue by nonufrienko** [riscv/riscv-aia#95]
Should mtopi/stopi always be zero when mnstatus.NMIE=0?

**Comment by jhauser-us** [comment]
No.  None of the "global" interrupt-enable bits, `mnstatus`.NMIE, `mstatus`.MIE, or `mstatus`/`sstatus`.SIE, have any effect on the values of `mip`, `mtopi`, `sip`, or `stopi`.

The AIA document is written without attention to Smrnmi, which can be interpreted as an extension that adds to AIA.  (If I remember correctly, Smaia was ratified before Smrnmi.)

**Comment by nonufrienko** [comment]
Thanks
